name: Cherry pick from main to release branches

on:
  pull_request_target:
    branches:
      - main
    types: ["closed"]

permissions: {}

jobs:
  get_branches:
    runs-on: ubuntu-latest
    name: Get branches to check-pick
    if: ${{ github.event.pull_request.merged == true }}
    outputs:
      CHERRY_PICK_BRANCHES: ${{ steps.get_and_extract_labels.outputs.CHERRY_PICK_BRANCHES }}

    steps:
      - name: Get and Extract cherry-pick labels
        id: get_and_extract_labels
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        with:
          script: |
            const labels = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            // Output the labels as a comma-separated list
            const labelNames = labels.data.map(label => label.name).join(',');
            console.log(`PR labels: ${labelNames}`);

            // Filter cherry-pick labels and extract branch names
            const cherryPickBranches = labels.data
              .map(label => label.name)
              .filter(name => name.startsWith('cherry-pick/'))
              .map(name => name.substring('cherry-pick/'.length));

            console.log(`Cherry-pick branches: ${cherryPickBranches}`);

            core.setOutput('CHERRY_PICK_BRANCHES', JSON.stringify(cherryPickBranches));

  cherry_pick:
    needs: get_branches
    runs-on: ubuntu-latest
    name: Create cherry-pick pull request
    permissions:
      pull-requests: write
      contents: write
    strategy:
      matrix:
        branch: ${{ fromJson(needs.get_branches.outputs.CHERRY_PICK_BRANCHES) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cherry pick to branch ${{ matrix.branch }}
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.10
        with:
          branch: ${{ matrix.branch }}
          body: "Cherry-pick of PR #${{ github.event.pull_request.number }} to branch ${{ matrix.branch }}."
          cherry-pick-branch: ${{ format('cherry-pick-{0}-{1}', github.event.number, matrix.branch) }}
          title: "[${{ matrix.branch }}] Cherry-pick: ${{ github.event.pull_request.title }}"
          labels: |
            cherry-pick
